apiVersion: v1
kind: Service
metadata:
  name: python-svc
spec:
  ports:
  - name: python-svc-port
    port: 8846
    targetPort: 5000
    nodePort: 30846
  selector:
    app: python
  type: NodePort
