apiVersion: apps/v1
kind: Deployment
metadata:
    name: python-deploy
    labels:
      app: python
spec:
    selector:
      matchLabels:
        app: python
    replicas: 1
    template:
      metadata:
        labels:
          app: python
      spec:
        containers:
          - name: python-svc
            image: rncortes1990/python-svc:1.0.0
            ports:
              - name: python-port
                containerPort: 5000