apiVersion: v1
kind: Pod
metadata:
    name: python-deploy
    labels:
      app: python
spec:
    containers:
        - name: python-svc
          image: rncortes1990/python-svc:1.0.0
          ports:
            - name: python-port
              containerPort: 5000
              